POST http://localhost:8080/api/auth/grade/51
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnb29kOTcxMkBuYXRlLmNvbSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MzgwODUwN30.mRvX1WrKBsdJzy7MEgbAATYRrczAEw1LXsE_xTA5GMc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjQzMjY5MDd9.lb4VrR5UdzFoQbRdrmKnkfIokwWruBq-lMTa0lwdPUE


### 마이페이지 유저 정보 GET
GET http://localhost:8080/api/auth/mypage
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnb29kOTcxMkBuYXRlLmNvbSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MzgwODUwN30.mRvX1WrKBsdJzy7MEgbAATYRrczAEw1LXsE_xTA5GMc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjQzMjY5MDd9.lb4VrR5UdzFoQbRdrmKnkfIokwWruBq-lMTa0lwdPUE

### 마이페이지 유저가 쓴 글 GET
GET http://localhost:8080/api/auth/mypage/myposts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnb29kOTcxMkBuYXRlLmNvbSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MzgwODUwN30.mRvX1WrKBsdJzy7MEgbAATYRrczAEw1LXsE_xTA5GMc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjQzMjY5MDd9.lb4VrR5UdzFoQbRdrmKnkfIokwWruBq-lMTa0lwdPUE

###모든 페이지 - 레시피 좋아요
POST http://localhost:8080/api/auth/post/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnb29kOTcxMkBuYXRlLmNvbSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MzkxNjcwNH0._qWbmpD0nawqfFnpcZLuXQ6sYxaKkvH1q5xDj2g3H9U
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjQ0MzUxMDR9.yrHBnLJppQOn5PZ4xxs_ZB0GJAnQfvetS7UeLEdsVig

###마이페이지 - 내가 좋아요한 레시피 GET
GET http://localhost:8080/api/auth/mypage/likeposts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnb29kOTcxMkBuYXRlLmNvbSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MzkxNjcwNH0._qWbmpD0nawqfFnpcZLuXQ6sYxaKkvH1q5xDj2g3H9U
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjQ0MzUxMDR9.yrHBnLJppQOn5PZ4xxs_ZB0GJAnQfvetS7UeLEdsVig

### 상세페이지 - 게시글 내용 GET
GET http://localhost:8080/api/post/3
Content-Type: application/json

### 상세페이지 - 댓글달기
POST http://localhost:8080/api/auth/post/3/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnb29kOTcxMkBuYXRlLmNvbSIsImF1dGgiOiJST0xFX01FTUJFUiIsImV4cCI6MTY2MzgwODUwN30.mRvX1WrKBsdJzy7MEgbAATYRrczAEw1LXsE_xTA5GMc
Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjQzMjY5MDd9.lb4VrR5UdzFoQbRdrmKnkfIokwWruBq-lMTa0lwdPUE

{
  "comment" : "이거보고 따라해봤는데 계란국 존맛 ,, 진짜 쉬워요 !!!"
}

### 특정 유저에게 칭호 POST
POST http://localhost:8080/api/grade/50/58
Content-Type: application/json

### 마이페이지 - 다른 유저의 정보 GET
GET http://localhost:8080/api/mypage/57
Content-Type: application/json

### 마이페이지 - 해당 유저가 쓴 글 GET
GET http://localhost:8080/api/mypage/1/myposts
Content-Type: application/json

